"""
Write the verdicts from `deliverables/verdicts.json` into `FAILURES.md`.

    uv run python -m tools.apply_verdicts           # apply
    uv run python -m tools.apply_verdicts --check   # exit 1 if the file is out of date

WHY THIS IS NOT JUST AN EDIT

`FAILURES.md` is generated by `rag/probe.py`, which hardcodes `UNVERIFIED` on every
verdict line. Verdicts typed straight into the markdown would survive exactly until
the next regeneration and then vanish, taking the human judgement with them — the
one part of that file a script cannot reproduce.

So the JSON is the record and the markdown renders from it. `probe.py` reads the same
file when it regenerates, which is why a rebuild now preserves verdicts instead of
resetting them.

WHAT IT DOES NOT DO

Decide anything, and not check the verdicts either. It moves confirmed judgements from
the record into the deliverable. The judging is D06's, and lives with a person.
"""

from __future__ import annotations

import json
import re
import sys

from rag import corpus

ROOT = corpus.REPO_ROOT
REPORT = ROOT / "deliverables" / "FAILURES.md"
RECORD = ROOT / "deliverables" / "verdicts.json"

VALID = {"CORRECT", "WRONG", "PARTIAL", "UNVERIFIED"}
LINE = re.compile(r"^\*\*Verdict:\*\* .*$", re.M)


def load() -> dict[str, list[str]]:
    """The verdict record, minus its README block."""
    return {k: v for k, v in json.loads(RECORD.read_text()).items()
            if not k.startswith("_")}


def render(text: str, verdicts: dict[str, list[str]]) -> tuple[str, int]:
    """Replace each entry's verdict line with the recorded one."""
    parts = re.split(r"^(## (\d+)\. .+)$", text, flags=re.M)
    out, applied = [parts[0]], 0
    for i in range(1, len(parts), 3):
        heading, num, body = parts[i], parts[i + 1], parts[i + 2]
        v = verdicts.get(num)
        if v:
            verdict, why = v[0], v[1]
            if verdict not in VALID:
                sys.exit(f"entry {num}: {verdict!r} is not one of {sorted(VALID)}")
            body, n = LINE.subn(f"**Verdict:** `{verdict}` — {why}", body, count=1)
            applied += n
        out += [heading, body]
    return "".join(out), applied


def main() -> None:
    """Apply the record, or check the deliverable is in sync with it."""
    verdicts = load()
    current = REPORT.read_text()
    updated, applied = render(current, verdicts)

    if "--check" in sys.argv[1:]:
        if updated != current:
            sys.exit("FAILURES.md is out of sync with verdicts.json — run tools.apply_verdicts")
        print(f"in sync: {applied} verdicts")
        return

    REPORT.write_text(updated)
    tally: dict[str, int] = {}
    for v in verdicts.values():
        tally[v[0]] = tally.get(v[0], 0) + 1
    counts = "  ".join(f"{k} {n}" for k, n in sorted(tally.items()))
    print(f"applied {applied} verdicts to {REPORT.relative_to(ROOT)}\n  {counts}")


if __name__ == "__main__":
    main()
