"""
Condense FAILURES.md into a sheet the 19 verdicts can actually be judged from.

    uv run python -m tools.review_sheet            # writes deliverables/VERDICTS.md
    uv run python -m tools.review_sheet --stdout   # print instead

WHY THIS EXISTS

`deliverables/FAILURES.md` is 2580 lines, because every entry carries the full
text of all five retrieved chunks. That is right for the record and wrong for
the job in front of a reader: marking 19 answers CORRECT / WRONG / PARTIAL.
This drops the chunk bodies, keeps the source list, and adds the one thing
FAILURES.md does not have — the verified answer.

WHERE THE VERIFIED ANSWER COMES FROM

`deliverables/BREAKAGES.md`, the Phase 0 deliverable: 23 breakages measured
against real 2.0.51, each with a fix marked `fix OK` by `verify_2_0.py`. That
is the same file `rag/probe.py` drew the questions from (D09 keeps it out of
the corpus, so asking about it is a fair test rather than a lookup).

**Six of the mappings are stated outright in probe.py's comments** — questions
to BREAKAGES #12, #13, #5, #6, #18, #10 and #23. The rest are matched here by
symbol to the breakage heading, and anything unmatched is reported as having no
key rather than guessed at. A wrong pairing is this file's fault, not
BREAKAGES', which is why the two sources of the mapping are kept distinct below.

WHAT THIS DOES NOT DO

Decide anything. Every entry ends with an empty verdict slot. D06 and D46
reserve the judgement for a person, and a sheet that pre-filled it would be the
answer key grading its own homework.
"""

from __future__ import annotations

import json
import re
import sys

from rag import corpus, probe

ROOT = corpus.REPO_ROOT
OUT = ROOT / "deliverables" / "VERDICTS.md"
OUT_FULL = ROOT / "deliverables" / "VERDICTS-FULL.md"
RECORD = ROOT / "deliverables" / "verdicts.json"

# Stated in probe.py's own comments — not inferred.
EXPLICIT = {
    "from_self": 12, "aliased": 13, "table_names": 5, "has_table": 6,
    "keys()": 18, "relation": 10, "cascade_backrefs": 23, "backref": 23,
}
# Matched by symbol to the breakage heading. Inference, and labelled as such.
INFERRED = {
    "autocommit": 20, "subtransaction": 21, "bind": 7, "select(": 8,
    "scalars": 16, "unique()": 19,
}

WHY = {
    "symbol": "exact symbol name — where dense retrieval is supposed to be weakest",
    "skew": "the answer differs between 1.4 and 2.0, so a wrong-version page is a wrong answer",
    "spanning": "the answer needs more than one chunk",
    "absent": "the corpus genuinely cannot answer — a refusal is the correct output",
    "silent": "a breakage that raises nothing, so the docs barely discuss it",
}


def breakages() -> dict[int, tuple[str, str]]:
    """Every BREAKAGES.md entry, keyed by its number."""
    text = (ROOT / "deliverables" / "BREAKAGES.md").read_text()
    b = re.split(r"^### (\d+)\. (.+)$", text, flags=re.M)[1:]
    return {int(b[i]): (b[i + 1], b[i + 2]) for i in range(0, len(b), 3)}


def key_for(symbol: str | None):
    """Returns (breakage number, how it was matched) or (None, None)."""
    if not symbol:
        return None, None
    if symbol in EXPLICIT:
        return EXPLICIT[symbol], "stated in probe.py"
    if symbol in INFERRED:
        return INFERRED[symbol], "matched by symbol — inferred here"
    return None, None


def fix_of(n: int, entries) -> dict:
    """The verified fix block for one breakage, plus the error it replaces."""
    heading, body = entries[n]
    m = re.search(r"\*\*Fix\*\* — _(.*?)_\s*\n\n```python\n(.*?)\n```", body, flags=re.S)
    err = re.search(r"\*\*2\.0 error\*\* — `(.+?)`", body)
    return {
        "n": n, "heading": heading,
        "status": m.group(1) if m else "(no fix block)",
        "code": m.group(2).strip() if m else "",
        "error": err.group(1) if err else "",
        "body": body,
    }


def build(full: bool = False) -> str:
    """The whole sheet, as markdown."""
    drafts = {}
    if RECORD.exists():
        drafts = {k: v for k, v in json.loads(RECORD.read_text()).items()
                  if not k.startswith("_")}
    known = breakages()
    keys = {}
    for question, _cat, sym in probe.QUESTIONS:
        n, how = key_for(sym)
        keys[question] = (fix_of(n, known) | {"how": how}) if n else None

    src = (ROOT / "deliverables" / "FAILURES.md").read_text()
    parts = re.split(r"^## (\d+)\. (.+)$", src, flags=re.M)[1:]
    entries = [(parts[i], parts[i + 1], parts[i + 2]) for i in range(0, len(parts), 3)]
    n_keys = sum(1 for v in keys.values() if v)
    counts: dict[str, int] = {}
    for v in drafts.values():
        counts[v[0]] = counts.get(v[0], 0) + 1
    tally = " · ".join(f"{k} {n}" for k, n in sorted(counts.items())) or "unjudged"

    out = [
        "# Verdict review sheet",
        "",
        f"**Generated by `tools/review_sheet.py`** from `FAILURES.md` and `BREAKAGES.md`. "
        f"{len(entries)} entries; **{n_keys} carry a verified answer** from Phase 0. "
        f"**{tally}**",
        "",
        "Chunk text is omitted — open `FAILURES.md` at the numbered entry when a judgement "
        "needs the full passage. Scores are worth reading against **0.540**, what two "
        "*unrelated* chunks average in this corpus (`study/10-RETRIEVAL.md` R2.5): a hit at "
        "0.61 is 0.07 above noise, not 61% confident.",
        "",
        "**Verdicts were drafted by Claude and accepted by Viraj on 2026-08-17**, by comparing "
        "each answer against its BREAKAGES.md key and, where the answer proposed code, running "
        "both on real 2.0.51. `verdicts.json` is the record; this file and `FAILURES.md` render "
        "from it. The mechanical signals (`D46`) locate problems; they never decided one.",
        "",
        "---",
        "",
    ]

    for num, question, body in entries:
        meta = re.search(r"^`(\w+)` · (.+?)$", body, flags=re.M)
        cat = meta.group(1) if meta else "?"
        sigm = re.search(r"\*\*Signals:\*\* (.+?)$", body, flags=re.M)
        # Anchor on the NEXT section, not the next closing fence: answers often
        # contain their own ```python block, and a non-greedy match stops inside it.
        ansm = re.search(r"### Answer\n\n```\n(.*?)\n```\s*\n+### ", body, flags=re.S)
        ans = ansm.group(1).strip() if ansm else "(no answer captured)"
        srcs = re.findall(
            r"\*\*\[(\d+)\]\*\* `([\d.]+)` · SQLAlchemy \*\*([\d.]+)\*\* · `(.+?)`\s*\n(.*?)\n",
            body,
        )
        # the full retrieved passage under each source, kept only in --full
        texts = re.findall(r"```rst\n(.*?)\n```", body, flags=re.S)

        out += [f"## {num}. {question}", "",
                f"**`{cat}`** — {WHY.get(cat, '')}",
                f"`{meta.group(2) if meta else ''}`",
                f"**Signals:** {sigm.group(1).strip() if sigm else '_none_'}", "",
                "**It answered:**", ""]
        out += ["> " + line for line in ans.splitlines()]
        out += ["", "**From:**", ""]
        for i, (n, score, ver, path, heading) in enumerate(srcs):
            over = float(score) - 0.540
            out.append(f"- `[{n}]` **{score}** (+{over:.3f} over noise) · {ver} · "
                       f"`{path.split('doc/build/')[-1]}`  ")
            out.append(f"  {heading.strip() or '(no heading)'}")
            if full and i < len(texts):
                out += ["", "  ```rst", *("  " + ln for ln in texts[i].splitlines()), "  ```", ""]
        out.append("")

        k = keys.get(question)
        if k:
            out += [f"**VERIFIED ANSWER** — BREAKAGES #{k['n']} · {k['heading']}  ",
                    f"_{k['status']}_ · 2.0 raises `{k['error']}` · _{k['how']}_", ""]
            if full and k.get("body"):
                out += ["<details><summary>the whole BREAKAGES entry</summary>", "",
                        k["body"].strip(), "", "</details>", ""]
            else:
                out += ["```python", k["code"], "```"]
        else:
            out.append("**No single answer key** — this question does not map to one "
                       "BREAKAGES entry; the answer is a judgement rather than a lookup.")
        d = drafts.get(str(num))
        if d:
            out += ["", f"**Verdict: `{d[0]}`** — {d[1]}"]
        else:
            out += ["", "**Verdict:** `________` — "]
        out += ["", "---", ""]

    return "\n".join(out)


def main() -> None:
    """Write the sheet, or print it with --stdout."""
    text = build(full="--full" in sys.argv[1:])
    if "--stdout" in sys.argv[1:]:
        print(text)
        return
    target = OUT_FULL if "--full" in sys.argv[1:] else OUT
    target.write_text(text)
    print(f"wrote {target.relative_to(ROOT)}  ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
